### ISSUE TITLE
Duration Disabled

### ISSUE THREAD

**Issue by ulaserdegor** [luispadron/LPSnackbar#2]
Hi. Nice work!
But i want always show this snack. Is it possible?
Thank you!

**Comment by luispadron** [comment]
Thanks!

As stated in the [docs](https://htmlpreview.github.io/?https://raw.githubusercontent.com/luispadron/LPSnackbar/master/docs/Classes/LPSnackbar.html#/s:10LPSnackbarAACABSS5title_SSSg11buttonTitleSdSg15displayDurationtcfc) 

If `displayDuration` is `nil`, the view will not be removed unless swiped away or button is pressed.

**Comment by ulaserdegor** [comment]
OMG. 
This is possible already 🥇 
displayDuration: nil

**Comment by ulaserdegor** [comment]
@luispadron at the same time!

Thank you!
