### ISSUE TITLE
titleLabel.numberOfLines doesn't work

### ISSUE THREAD

**Issue by JaDenis** [luispadron/LPSnackbar#4]
Hi!
Cool framework, i'd like a clarification on how to make titleLabel multi-line.

**Comment by luispadron** [comment]
The implementation of the label is just a UILabel.
I'm not sure what exactly needs to be set. 
But it should work as a normal UILabel.

**Comment by JaDenis** [comment]
thanks for quick reply! 
i tried 
`.   snackView.titleLabel.numberOfLines = 0`
```
snackView.titleLabel.numberOfLines = 1
snackView.titleLabel.adjustsFontSizeToFitWidth = true
snackView.titleLabel.minimumScaleFactor = 0.1
```

both do nothing, maybe something resets titleLabel before rendering.. idk)

**Comment by luispadron** [comment]
I don't have time to look at this right now, but I will whenever I get a chance.
You can also take a look at the source and see if you can figure it out, the LPSnackbarView is the one responsible for laying things out.

**Comment by luispadron** [comment]
Just tested this, and it's working as expected.
Heres an example of a snackbar with multiple lines of texts.

```swift
let snack = LPSnackbar(title: "Snack deleted!\nThis is another line of text\nAnd another one", buttonTitle: "UNDO")
snack.view.titleLabel.numberOfLines = 0
snack.view.titleLabel.sizeToFit()
snack.height = snack.view.titleLabel.frame.size.height + 10
```

The above modifies the snack's underlying label to contain an infinite amount of lines, it then sizes the label which gives us the proper height for the label. It then tells the snack that it's height should be the height of the label plus some extra padding.

This is kind of inconvenient and maybe snack's should resize to fit their labels, however, I do not want to complicate the code and would like to keep this as lightweight as possible. Also, snackbars are not the best thing to use for lots of texts, they're meant for small digestible information.

I'm closing this issue as the above code should do what you have asked, sorry it took this long for me to look at it.
