### ISSUE TITLE
Support for multiline snackbar

### ISSUE THREAD

**Issue by Koronaa** [luispadron/LPSnackbar#8]
Hey,

It seems currently that the snackbar supports only single line.

Would it possible to set support for multiline snackbar so that I can avoid below scenario? 

<img width="359" alt="Untitled" src="https://user-images.githubusercontent.com/11703410/55228702-d798a300-5240-11e9-82f7-c777d8ae6459.png">

Thanks!

**Comment by luispadron** [comment]
Please take a look at #4
